# Generated by Django 4.1.5 on 2023-02-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kvart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(max_length=255)),
                ('prise', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
